name: appimagepool
description: A simple, modern AppImageHub Client made for linux using flutter.

version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window: ^0.1.1+1
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  dio: ^4.0.0
  file_picker: ^4.0.0
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  gtk: ^0.2.3
  hooks_riverpod: ^1.0.0-dev.6
  package_info_plus: ^1.0.4
  path_provider: ^2.0.2
  process_run: ^0.12.1
  simple_html_css: ^3.0.1
  sticky_headers: ^0.2.0
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
