name: appimagebrowser
description: A new Flutter project.

version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0-nullsafety.0
  flutter_hooks: ^0.16.0
  cached_network_image: ^3.0.0
  dio: ^4.0.0
  flutter_svg: ^0.21.0+1
  flutter_staggered_grid_view: ^0.4.0
  material_floating_search_bar: ^0.3.3
  path_provider: ^2.0.1
  process_run: ^0.12.1
  simple_html_css: ^3.0.1
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # assets:
  #  - assets/images/

  # fonts:
  #   - family: Montserrat
  #     fonts:
  #       - asset: assets/fonts/Montserrat-Regular.ttf
  #       - asset: assets/fonts/Montserrat-SemiBold.ttf
  #       - asset: assets/fonts/Montserrat-Bold.ttf