name: appimagebrowser
description: A new Flutter project.

version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0-nullsafety.0
  dio: ^4.0.0
  flutter_svg: ^0.21.0-nullsafety.0
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # assets:
  #  - assets/images/
