name: appimagepool
description: A simple, modern AppImageHub Client made for linux using flutter.

version: 2.6.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adwaita_icons: ^0.2.0
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  desktop_notifications: ^0.6.0
  dio: ^4.0.0
  file_picker: ^4.0.0
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  gtk: ^0.8.5
  hooks_riverpod: ^1.0.0-dev.7
  intl: ^0.17.0
  nativeshell: ^0.1.9
  package_info_plus: ^1.0.5
  path_provider: ^2.0.2
  shared_preferences: ^2.0.6
  simple_html_css: ^3.0.1
  sticky_headers: ^0.2.0
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
