name: FlutterCI

on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - "README.md"
      - "docs/**"
      - "assets/screenshot/**"
  workflow_dispatch:
  release:
    types: created

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: haya14busa/action-cond@v1
        id: newref
        with:
          cond:  github.event_name == 'release'
          if_true: ${{github.ref}}
          if_false: ${{github.ref}}-nightly

      - name: Setup flutter
        uses: subosito/flutter-action@master
        with:
          channel: beta

      - name: Install linux app dependencies
        run: sudo apt-get update -y && sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Enable desktop support
        run: flutter config --enable-linux-desktop

      - name: Build Flutter app
        run: cargo build --release

      - name: Build AppImage
        run: ./create_appimage.sh

      - name: Compress AppDir
        run: tar czf appimagepool-x86_64.tar.gz -C AppDir/ . 

      - name: App tar sha256 sum
        run: sha256sum appimagepool-x86_64.tar.gz

      - uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./appimagepool-x86_64*
          file_glob: true
          tag: ${{ steps.newref.outputs.value }}
          body: Always up to date
          overwrite: true
